# config/profiles/world/country_aliases.yaml

# Spain
sp: ES
esp: ES
spa: ES
spain: ES
españa: ES
espana: ES

# United States
usa: US
us: US
united states: US
unitedstates: US
eeuu: US
euu: US

# Denmark
denmark: DK
dinamark: DK
dinamarca: DK
danmark: DK

# United Kingdom (pycountry a veces lía UK/GB)
uk: GB
u k: GB
u.k: GB
u.k.: GB
united kingdom: GB
great britain: GB
britain: GB
england: GB

# Switzerland (si la usas)
switzerland: CH
suisse: CH
schweiz: CH
svizzera: CH

# Germany
germany: DE
alemania: DE
alemán: DE
alemana: DE
deutschland: DE
deutsch: DE
alemao: DE

# Russia
russia: RU
russian federation: RU
russian fed: RU
russian fed.: RU
russian: RU
ruso: RU
rusa: RU
rusia: RU

# argelia
algeria: DZ
argelia: DZ

# Common “gotchas” / language variants
south korea: KR
korea: KR
north korea: KP
russia: RU
czech republic: CZ
czechia: CZ
taiwan: TW